// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package smd

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"
	"strconv"
	"time"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// Session represents a user session for revocation tracking
type Session struct {
	ID             string
	SuspicionScore int
	client         *dynamodb.Client
	tableName      string
	debug          bool
}

// SessionManager manages session operations
type SessionManager struct {
	client    *dynamodb.Client
	tableName string
	debug     bool
}

// NewSessionManager creates a new SessionManager
func NewSessionManager(tableName string, debug bool) (*SessionManager, error) {
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		return nil, fmt.Errorf("failed to load AWS config: %w", err)
	}

	return &SessionManager{
		client:    dynamodb.NewFromConfig(cfg),
		tableName: tableName,
		debug:     debug,
	}, nil
}

// NewSession creates a new session with the given ID
func (sm *SessionManager) NewSession(id string, suspicionScore int) *Session {
	return &Session{
		ID:             id,
		SuspicionScore: suspicionScore,
		client:         sm.client,
		tableName:      sm.tableName,
		debug:          sm.debug,
	}
}

// NewAutoGeneratedSession creates a new session with auto-generated ID
func (sm *SessionManager) NewAutoGeneratedSession(length int, suspicionScore int) (*Session, error) {
	if length <= 6 {
		return nil, fmt.Errorf("session ID length must be greater than 6")
	}

	id, err := generateRandomString(length)
	if err != nil {
		return nil, fmt.Errorf("failed to generate session ID: %w", err)
	}

	return &Session{
		ID:             id,
		SuspicionScore: suspicionScore,
		client:         sm.client,
		tableName:      sm.tableName,
		debug:          sm.debug,
	}, nil
}

// Revoke adds the session to the revocation table
func (s *Session) Revoke(ctx context.Context, expiryPeriod time.Duration, reason string) error {
	if s.client == nil {
		return fmt.Errorf("DynamoDB client not initialized")
	}

	if s.tableName == "" {
		return fmt.Errorf("revocation table name not set")
	}

	currentTimestamp := time.Now().Unix()
	expiryTime := currentTimestamp + int64(expiryPeriod.Seconds())

	item := map[string]types.AttributeValue{
		"session_id": &types.AttributeValueMemberS{
			Value: s.ID,
		},
		"type": &types.AttributeValueMemberS{
			Value: "MANUAL",
		},
		"score": &types.AttributeValueMemberN{
			Value: strconv.Itoa(s.SuspicionScore),
		},
		"reason": &types.AttributeValueMemberS{
			Value: reason,
		},
		"last_updated": &types.AttributeValueMemberN{
			Value: strconv.FormatInt(currentTimestamp, 10),
		},
		"ttl": &types.AttributeValueMemberN{
			Value: strconv.FormatInt(expiryTime, 10),
		},
	}

	_, err := s.client.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: &s.tableName,
		Item:      item,
	})

	if err != nil {
		s.debugLog(fmt.Sprintf("Failed to revoke session %s: %v", s.ID, err))
		return fmt.Errorf("failed to revoke session: %w", err)
	}

	s.debugLog(fmt.Sprintf("Successfully revoked session %s", s.ID))
	return nil
}

// generateRandomString generates a random string of specified length
func generateRandomString(length int) (string, error) {
	const charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
	result := make([]byte, length)

	for i := range result {
		num, err := rand.Int(rand.Reader, big.NewInt(int64(len(charset))))
		if err != nil {
			return "", err
		}
		result[i] = charset[num.Int64()]
	}

	return string(result), nil
}

// debugLog logs debug messages if debug mode is enabled
func (s *Session) debugLog(message string) {
	if s.debug {
		fmt.Printf("[DEBUG] Session: %s\n", message)
	}
}
