// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	smd "github.com/aws-solutions/secure-media-delivery-go"
)

func main() {
	fmt.Println("AWS Secure Media Delivery Go SDK - Basic Usage Example")
	fmt.Println("=====================================================")

	ctx := context.Background()

	// Initialize secret manager with debug enabled
	secret, err := smd.NewSecretManager("MySecureStreamStack", 5*time.Minute, smd.WithDebug(true))
	if err != nil {
		log.Fatalf("Failed to create secret manager: %v", err)
	}

	// Create token generator with debug enabled
	token := smd.NewTokenGenerator(secret, smd.WithTokenDebug(true))

	// Define viewer attributes
	viewerAttrs := &smd.ViewerAttributes{
		IP:      "192.168.1.100",
		Country: "US",
		Region:  "CA",
		City:    "San Francisco",
		Headers: map[string]string{
			"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
			"referer":    "https://example.com/player",
		},
		QueryVars: map[string]string{
			"quality": "1080p",
			"lang":    "en",
		},
	}

	// Define token policy
	policy := &smd.TokenPolicy{
		IP:                  true,
		Country:             true,
		CountryFallback:     true,
		Headers:             []string{"user-agent", "referer"},
		QueryStrings:        []string{"quality"},
		Paths:               []string{"/video/", "/live/"},
		Exclusions:          []string{"/health", "/status"},
		Exp:                 "+2h",
		Session:             true,
		SessionAutoGenerate: 16,
	}

	// Generate token for HLS stream
	fmt.Println("\nGenerating token for HLS stream...")
	hlsURL := "https://d1234567890.cloudfront.net/video/stream.m3u8"
	signedHLSURL, err := token.Generate(ctx, viewerAttrs, hlsURL, policy)
	if err != nil {
		log.Printf("Error generating HLS token: %v", err)
	} else {
		fmt.Printf("Signed HLS URL: %s\n", signedHLSURL)
	}

	// Generate token for DASH stream
	fmt.Println("\nGenerating token for DASH stream...")
	dashURL := "https://d1234567890.cloudfront.net/video/stream.mpd"
	signedDASHURL, err := token.Generate(ctx, viewerAttrs, dashURL, policy)
	if err != nil {
		log.Printf("Error generating DASH token: %v", err)
	} else {
		fmt.Printf("Signed DASH URL: %s\n", signedDASHURL)
	}

	// Generate standalone token
	fmt.Println("\nGenerating standalone token...")
	standaloneToken, err := token.Generate(ctx, viewerAttrs, "", policy)
	if err != nil {
		log.Printf("Error generating standalone token: %v", err)
	} else {
		fmt.Printf("Standalone token: %s\n", standaloneToken)
	}

	// Session management example
	sessionManagementExample(ctx)

	// Custom secret retrieval example
	customSecretExample(ctx)
}

func sessionManagementExample(ctx context.Context) {
	fmt.Println("\n" + strings.Repeat("=", 50))
	fmt.Println("Session Management Example")
	fmt.Println(strings.Repeat("=", 50))

	// Initialize session manager
	sessionMgr, err := smd.NewSessionManager("MyRevocationTable", true)
	if err != nil {
		log.Printf("Failed to create session manager: %v", err)
		return
	}

	// Create session with auto-generated ID
	session1, err := sessionMgr.NewAutoGeneratedSession(12, 0)
	if err != nil {
		log.Printf("Failed to create auto-generated session: %v", err)
		return
	}
	fmt.Printf("Auto-generated session ID: %s\n", session1.ID)

	// Create session with specific ID
	session2 := sessionMgr.NewSession("user-session-12345", 0)
	fmt.Printf("Custom session ID: %s\n", session2.ID)

	// Create session with custom length
	session3, err := sessionMgr.NewAutoGeneratedSession(20, 75)
	if err != nil {
		log.Printf("Failed to create custom length session: %v", err)
		return
	}
	fmt.Printf("Custom length session ID: %s\n", session3.ID)

	// Revoke a session
	fmt.Printf("\nRevoking session: %s\n", session2.ID)
	err = session2.Revoke(ctx, 24*time.Hour, "SUSPICIOUS_ACTIVITY")
	if err != nil {
		log.Printf("Error revoking session: %v", err)
	} else {
		fmt.Println("Session revoked successfully")
	}
}

func customSecretExample(ctx context.Context) {
	fmt.Println("\n" + strings.Repeat("=", 50))
	fmt.Println("Custom Secret Retrieval Example")
	fmt.Println(strings.Repeat("=", 50))

	// Custom secret retrieval function
	customRetriever := func(ctx context.Context, stackName string) (*smd.SecretKeys, error) {
		fmt.Printf("Custom retrieval for stack: %s\n", stackName)

		// In a real implementation, you might retrieve from:
		// - A different AWS service
		// - A local file
		// - An external API
		// - A database

		return &smd.SecretKeys{
			Primary: &smd.SecretKey{
				UUID:  "custom-key-uuid-12345",
				Value: "custom-secret-value-abcdef",
			},
			Secondary: &smd.SecretKey{
				UUID:  "custom-key-uuid-67890",
				Value: "custom-secret-value-ghijkl",
			},
		}, nil
	}

	// Initialize secret with custom retrieval
	secret, err := smd.NewSecretManager(
		"MyStack",
		5*time.Minute,
		smd.WithCustomRetriever(customRetriever),
		smd.WithDebug(true),
	)
	if err != nil {
		log.Printf("Failed to create custom secret manager: %v", err)
		return
	}

	// Retrieve keys using custom function
	keys, err := secret.RetrieveKeys(ctx, "all")
	if err != nil {
		log.Printf("Error with custom secret retrieval: %v", err)
		return
	}

	fmt.Printf("Retrieved keys: primary=%s, secondary=%s\n",
		keys.Primary.UUID,
		keys.Secondary.UUID)
}
