# frozen_string_literal: true

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# Specify your gem's dependencies in aws-secure-media-delivery.gemspec
gemspec

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.21'
gem 'yard', '~> 0.9'
gem 'simplecov', '~> 0.21'
